spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE}

logging:
  structured:
    format:
      console: logstash
  level:
    root: INFO
    com.streakup: INFO

app:
  cors:
    allowed-origins: ${APP_FRONTEND_ORIGIN}
  s3:
    region: ${AWS_REGION}
    bucket: ${AWS_S3_BUCKET}
